#!/bin/bash
set -euf -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/check-args.sh"
check_args "$0" "vm_name" "" "iso-path" "" "$@"
iso_path="$1"

VBoxManage storageattach "$vm_name" --storagectl IDE --port 0 --device 0 --type dvddrive --medium "$iso_path"
