#!/bin/bash
set -euf -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/check-args.sh"
check_args "$0" "vm_name" "" "" "" "$@"
export_path="$vm_name.ova"

VBoxManage export "$vm_name" --output "$export_path" --options manifest,nomacs
