#!/bin/bash
set -euf -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/check-args.sh"
check_args "$0" "" "" "import-path" "" "$@"
import_path="$1"

VBoxManage import "$import_path"
