#!/bin/bash
set -euf -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/check-args.sh"
check_args "$0" "vm_name os_type" "" "iso-path" "" "$@"
iso_path="$1"

VBoxManage modifyvm "$vm_name" --ostype "$os_type"
"$DIR/dvd-attach" "$iso_path"
"$DIR/start-gui"

printf '\nTo boot off the hard drive, eject the installation DVD by running:\n%s\n' "vm_name='$vm_name' $DIR/dvd-detach"
