#!/bin/bash
set -euf -o pipefail

: ${cable_connected='on'}
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/check-args.sh"
check_args "$0" "vm_name" "cable_connected" "" "" "$@"

VBoxManage modifyvm "$vm_name" --nic1 nat --cableconnected1 "$cable_connected"
