#!/bin/bash
set -euf -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/check-args.sh"
check_args "$0" "vm_name" "" "" "" "$@"

VBoxManage showvminfo "$vm_name" --machinereadable | grep Forwarding | awk -F'"' '{print $2}' | awk -F',' '{print $1}'
